/*
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class GraphQLWebModule extends AbstractGraphQLWebModule {
}
