/*
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link GraphQLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractGraphQLWebModule extends DefaultWebModule {

}
