/*
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GraphQLRuntimeModule extends AbstractGraphQLRuntimeModule {
}
