/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.web;

import co7217.miniproject2.GraphQLRuntimeModule;
import co7217.miniproject2.GraphQLStandaloneSetup;
import co7217.miniproject2.ide.GraphQLIdeModule;
import co7217.miniproject2.web.GraphQLWebModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class GraphQLWebSetup extends GraphQLStandaloneSetup {
  @Override
  public Injector createInjector() {
    GraphQLRuntimeModule _graphQLRuntimeModule = new GraphQLRuntimeModule();
    GraphQLIdeModule _graphQLIdeModule = new GraphQLIdeModule();
    GraphQLWebModule _graphQLWebModule = new GraphQLWebModule();
    return Guice.createInjector(Modules2.mixin(_graphQLRuntimeModule, _graphQLIdeModule, _graphQLWebModule));
  }
}
