/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.web;

import co7217.miniproject2.web.AbstractGraphQLWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class GraphQLWebModule extends AbstractGraphQLWebModule {
}
