/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.validation;

import co7217.miniproject2.validation.AbstractGraphQLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GraphQLValidator extends AbstractGraphQLValidator {
}
