/*
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGraphQLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(co7217.miniproject2.graphQL.GraphQLPackage.eINSTANCE);
		return result;
	}
	
}
