/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.ide;

import co7217.miniproject2.GraphQLRuntimeModule;
import co7217.miniproject2.GraphQLStandaloneSetup;
import co7217.miniproject2.ide.GraphQLIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GraphQLIdeSetup extends GraphQLStandaloneSetup {
  @Override
  public Injector createInjector() {
    GraphQLRuntimeModule _graphQLRuntimeModule = new GraphQLRuntimeModule();
    GraphQLIdeModule _graphQLIdeModule = new GraphQLIdeModule();
    return Guice.createInjector(Modules2.mixin(_graphQLRuntimeModule, _graphQLIdeModule));
  }
}
