/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.ide;

import co7217.miniproject2.ide.AbstractGraphQLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GraphQLIdeModule extends AbstractGraphQLIdeModule {
}
