/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.graphQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graph QL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.miniproject2.graphQL.GraphQL#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see co7217.miniproject2.graphQL.GraphQLPackage#getGraphQL()
 * @model
 * @generated
 */
public interface GraphQL extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link co7217.miniproject2.graphQL.AbstractElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see co7217.miniproject2.graphQL.GraphQLPackage#getGraphQL_Elements()
   * @model containment="true"
   * @generated
   */
  EList<AbstractElement> getElements();

} // GraphQL
