/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.graphQL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.miniproject2.graphQL.QueryField#getName <em>Name</em>}</li>
 *   <li>{@link co7217.miniproject2.graphQL.QueryField#getNestedQuery <em>Nested Query</em>}</li>
 * </ul>
 *
 * @see co7217.miniproject2.graphQL.GraphQLPackage#getQueryField()
 * @model
 * @generated
 */
public interface QueryField extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co7217.miniproject2.graphQL.GraphQLPackage#getQueryField_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co7217.miniproject2.graphQL.QueryField#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Nested Query</b></em>' containment reference list.
   * The list contents are of type {@link co7217.miniproject2.graphQL.QueryField}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nested Query</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nested Query</em>' containment reference list.
   * @see co7217.miniproject2.graphQL.GraphQLPackage#getQueryField_NestedQuery()
   * @model containment="true"
   * @generated
   */
  EList<QueryField> getNestedQuery();

} // QueryField
