/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.graphQL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co7217.miniproject2.graphQL.Query#getQueryField <em>Query Field</em>}</li>
 * </ul>
 *
 * @see co7217.miniproject2.graphQL.GraphQLPackage#getQuery()
 * @model
 * @generated
 */
public interface Query extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Query Field</b></em>' containment reference list.
   * The list contents are of type {@link co7217.miniproject2.graphQL.QueryField}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Query Field</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query Field</em>' containment reference list.
   * @see co7217.miniproject2.graphQL.GraphQLPackage#getQuery_QueryField()
   * @model containment="true"
   * @generated
   */
  EList<QueryField> getQueryField();

} // Query
