/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.graphQL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co7217.miniproject2.graphQL.GraphQLPackage#getType()
 * @model
 * @generated
 */
public interface Type extends AbstractElement
{
} // Type
