/*
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.serializer;

import co7217.miniproject2.services.GraphQLGrammarAccess;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class GraphQLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected GraphQLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Feature_ExclamationMarkKeyword_0_3_q;
	protected AbstractElementAlias match_Feature_ExclamationMarkKeyword_1_4_q;
	protected AbstractElementAlias match_Feature_ExclamationMarkKeyword_1_6_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (GraphQLGrammarAccess) access;
		match_Feature_ExclamationMarkKeyword_0_3_q = new TokenAlias(false, true, grammarAccess.getFeatureAccess().getExclamationMarkKeyword_0_3());
		match_Feature_ExclamationMarkKeyword_1_4_q = new TokenAlias(false, true, grammarAccess.getFeatureAccess().getExclamationMarkKeyword_1_4());
		match_Feature_ExclamationMarkKeyword_1_6_q = new TokenAlias(false, true, grammarAccess.getFeatureAccess().getExclamationMarkKeyword_1_6());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Feature_ExclamationMarkKeyword_0_3_q.equals(syntax))
				emit_Feature_ExclamationMarkKeyword_0_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Feature_ExclamationMarkKeyword_1_4_q.equals(syntax))
				emit_Feature_ExclamationMarkKeyword_1_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Feature_ExclamationMarkKeyword_1_6_q.equals(syntax))
				emit_Feature_ExclamationMarkKeyword_1_6_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '!'?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=[Type|ID] (ambiguity) (rule end)
	 */
	protected void emit_Feature_ExclamationMarkKeyword_0_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '!'?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=[Type|ID] (ambiguity) ']' '!'? (rule end)
	 */
	protected void emit_Feature_ExclamationMarkKeyword_1_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '!'?
	 *
	 * This ambiguous syntax occurs at:
	 *     type=[Type|ID] '!'? ']' (ambiguity) (rule end)
	 */
	protected void emit_Feature_ExclamationMarkKeyword_1_6_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
