/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.graphQL.impl;

import co7217.miniproject2.graphQL.GraphQLPackage;
import co7217.miniproject2.graphQL.Scalar;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Scalar</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ScalarImpl extends TypeImpl implements Scalar
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScalarImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GraphQLPackage.Literals.SCALAR;
  }

} //ScalarImpl
