/*
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.tests

import co7217.miniproject2.graphQL.GraphQL
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(GraphQLInjectorProvider)
class GraphQLParsingTest {
	@Inject
	ParseHelper<GraphQL> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
