/**
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.scoping;

import co7217.miniproject2.scoping.AbstractGraphQLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GraphQLScopeProvider extends AbstractGraphQLScopeProvider {
}
