/*
 * generated by Xtext 2.12.0
 */
package co7217.miniproject2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGraphQLScopeProvider extends DelegatingScopeProvider {
}
